const CategoryListingConstants = {

  CATEGORY_LISTINGS_RECEIVED: "CATEGORY_LISTINGS_RECEIVED",
  CATEGORY_LISTING_RECEIVED: "CATEGORY_LISTING_RECEIVED",
  CATEGORY_LISTING_REMOVED: "CATEGORY_LISTING_REMOVED"


};

module.exports = CategoryListingConstants;
