const CategoryConstants = {

  CATEGORY_RECEIVED: "CATEGORY_RECEIVED",
  CATEGORIES_RECEIVED: "CATEGORIES_RECEIVED",
  CATEGORY_REMOVED: "CATEGORY_REMOVED"
  


};

module.exports = CategoryConstants;
